version: '3'
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  backend:
    build:
      context: .
    environment:
     - DATABASE_URL=db
     - DATABASE_USERNAME=postgres
     - DATABASE_PASSWORD=password
     - DATABASE_PORT=5432
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    command: make start

  frontend:
    build:
      context: .
    volumes:
      - ./frontend:/frontend
    command: make start


  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
